server:
  port: 8022
  context-path: /rabbitmq-consumer
spring:
  datasource:
    url: jdbc:mysql://192.168.2.8:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  #给项目来个名字
  application:
    name: rabbitmq-consumer
  #配置rabbitMq 服务器
  rabbitmq:
      host: 192.168.2.8
      port: 5672
      username: guest
      password: guest
      virtual-host: /
    #虚拟host 可以不设置,使用server默认host
    #virtual-host: JCcccHost
      #确认消息已发送到交换机(Exchange)
      publisher-confirm-type: correlated
      #确认消息已发送到队列(Queue)
      publisher-returns-type: correlated

